
#include "IFParamsMacro.h"


#undef IF_DP_TARGET_FUNCTION_PARAM_DEFINE
#undef IF_DP_TARGET_FUNCTION_PARAM_CALL
#undef IF_DP_TARGET_TEMPALTE_PARAM_DEFINE

//#define IF_DP_TARGET_FUNCTION_PARAM_NUM 9

#if		IF_DP_TARGET_FUNCTION_PARAM_NUM <= 0 
#define IF_DP_TARGET_FUNCTION_PARAM_DEFINE(PP,pp) 
#define IF_DP_TARGET_FUNCTION_PARAM_CALL(P) 
#define IF_DP_TARGET_TEMPALTE_PARAM_DEFINE(P) 

#elif	IF_DP_TARGET_FUNCTION_PARAM_NUM <= 1
#define IF_DP_TARGET_FUNCTION_PARAM_DEFINE(PP,pp)		IF_FUNCTION_PARAM_DEFINE0(PP,pp)
#define IF_DP_TARGET_FUNCTION_PARAM_CALL(P)			IF_FUNCTION_PARAM_CALL0(P) 
#define IF_DP_TARGET_TEMPALTE_PARAM_DEFINE(P)			IF_TEMPALTE_PARAM_DEFINE0(P) 

#elif	IF_DP_TARGET_FUNCTION_PARAM_NUM <= 2
#define IF_DP_TARGET_FUNCTION_PARAM_DEFINE(PP,pp)		IF_FUNCTION_PARAM_DEFINE1(PP,pp)
#define IF_DP_TARGET_FUNCTION_PARAM_CALL(P)			IF_FUNCTION_PARAM_CALL1(P) 
#define IF_DP_TARGET_TEMPALTE_PARAM_DEFINE(P)			IF_TEMPALTE_PARAM_DEFINE1(P) 

#elif	IF_DP_TARGET_FUNCTION_PARAM_NUM <= 3
#define IF_DP_TARGET_FUNCTION_PARAM_DEFINE(PP,pp)		IF_FUNCTION_PARAM_DEFINE2(PP,pp)
#define IF_DP_TARGET_FUNCTION_PARAM_CALL(P)			IF_FUNCTION_PARAM_CALL2(P) 
#define IF_DP_TARGET_TEMPALTE_PARAM_DEFINE(P)			IF_TEMPALTE_PARAM_DEFINE2(P) 

#elif	IF_DP_TARGET_FUNCTION_PARAM_NUM <= 4
#define IF_DP_TARGET_FUNCTION_PARAM_DEFINE(PP,pp)		IF_FUNCTION_PARAM_DEFINE3(PP,pp)
#define IF_DP_TARGET_FUNCTION_PARAM_CALL(P)			IF_FUNCTION_PARAM_CALL3(P) 
#define IF_DP_TARGET_TEMPALTE_PARAM_DEFINE(P)			IF_TEMPALTE_PARAM_DEFINE3(P) 

#elif	IF_DP_TARGET_FUNCTION_PARAM_NUM <= 5
#define IF_DP_TARGET_FUNCTION_PARAM_DEFINE(PP,pp)		IF_FUNCTION_PARAM_DEFINE4(PP,pp)
#define IF_DP_TARGET_FUNCTION_PARAM_CALL(P)			IF_FUNCTION_PARAM_CALL4(P) 
#define IF_DP_TARGET_TEMPALTE_PARAM_DEFINE(P)			IF_TEMPALTE_PARAM_DEFINE4(P) 

#elif	IF_DP_TARGET_FUNCTION_PARAM_NUM <= 6
#define IF_DP_TARGET_FUNCTION_PARAM_DEFINE(PP,pp)		IF_FUNCTION_PARAM_DEFINE5(PP,pp)
#define IF_DP_TARGET_FUNCTION_PARAM_CALL(P)			IF_FUNCTION_PARAM_CALL5(P) 
#define IF_DP_TARGET_TEMPALTE_PARAM_DEFINE(P)			IF_TEMPALTE_PARAM_DEFINE5(P) 

#elif	IF_DP_TARGET_FUNCTION_PARAM_NUM <= 7
#define IF_DP_TARGET_FUNCTION_PARAM_DEFINE(PP,pp)		IF_FUNCTION_PARAM_DEFINE6(PP,pp)
#define IF_DP_TARGET_FUNCTION_PARAM_CALL(P)			IF_FUNCTION_PARAM_CALL6(P) 
#define IF_DP_TARGET_TEMPALTE_PARAM_DEFINE(P)			IF_TEMPALTE_PARAM_DEFINE6(P) 

#elif	IF_DP_TARGET_FUNCTION_PARAM_NUM <= 8
#define IF_DP_TARGET_FUNCTION_PARAM_DEFINE(PP,pp)		IF_FUNCTION_PARAM_DEFINE7(PP,pp)
#define IF_DP_TARGET_FUNCTION_PARAM_CALL(P)			IF_FUNCTION_PARAM_CALL7(P) 
#define IF_DP_TARGET_TEMPALTE_PARAM_DEFINE(P)			IF_TEMPALTE_PARAM_DEFINE7(P) 

#elif	IF_DP_TARGET_FUNCTION_PARAM_NUM <= 9
#define IF_DP_TARGET_FUNCTION_PARAM_DEFINE(PP,pp)		IF_FUNCTION_PARAM_DEFINE8(PP,pp)
#define IF_DP_TARGET_FUNCTION_PARAM_CALL(P)			IF_FUNCTION_PARAM_CALL8(P) 
#define IF_DP_TARGET_TEMPALTE_PARAM_DEFINE(P)			IF_TEMPALTE_PARAM_DEFINE8(P) 

#elif	IF_DP_TARGET_FUNCTION_PARAM_NUM <= 10
#define IF_DP_TARGET_FUNCTION_PARAM_DEFINE(PP,pp)		IF_FUNCTION_PARAM_DEFINE9(PP,pp)
#define IF_DP_TARGET_FUNCTION_PARAM_CALL(P)			IF_FUNCTION_PARAM_CALL9(P) 
#define IF_DP_TARGET_TEMPALTE_PARAM_DEFINE(P)			IF_TEMPALTE_PARAM_DEFINE9(P) 
#else
#error	NOT SUPPORT PARAM NUM > 10
#endif


#undef IF_DP_SRC_FUNCTION_PARAM_NUM
#define IF_DP_SRC_FUNCTION_PARAM_NUM (IF_FUNCTION_PARAM_NUM - IF_DP_TARGET_FUNCTION_PARAM_NUM)

#if IF_DP_SRC_FUNCTION_PARAM_NUM > 0

#undef IF_DP_SRC_FUNCTION_PARAM_DEFINE
#undef IF_DP_SRC_FUNCTION_PARAM_CALL
#undef IF_DP_SRC_TEMPALTE_PARAM_DEFINE

#if		IF_DP_SRC_FUNCTION_PARAM_NUM <= 0 
#define IF_DP_SRC_FUNCTION_PARAM_DEFINE(PP,pp) 
#define IF_DP_SRC_FUNCTION_PARAM_CALL(P) 
#define IF_DP_SRC_TEMPALTE_PARAM_DEFINE(P) 

#elif	IF_DP_SRC_FUNCTION_PARAM_NUM <= 1
#define IF_DP_SRC_FUNCTION_PARAM_DEFINE(PP,pp)		IF_FUNCTION_PARAM_DEFINE0(PP,pp)
#define IF_DP_SRC_FUNCTION_PARAM_CALL(P)			IF_FUNCTION_PARAM_CALL0(P) 
#define IF_DP_SRC_TEMPALTE_PARAM_DEFINE(P)			IF_TEMPALTE_PARAM_DEFINE0(P) 

#elif	IF_DP_SRC_FUNCTION_PARAM_NUM <= 2
#define IF_DP_SRC_FUNCTION_PARAM_DEFINE(PP,pp)		IF_FUNCTION_PARAM_DEFINE1(PP,pp)
#define IF_DP_SRC_FUNCTION_PARAM_CALL(P)			IF_FUNCTION_PARAM_CALL1(P) 
#define IF_DP_SRC_TEMPALTE_PARAM_DEFINE(P)			IF_TEMPALTE_PARAM_DEFINE1(P) 

#elif	IF_DP_SRC_FUNCTION_PARAM_NUM <= 3
#define IF_DP_SRC_FUNCTION_PARAM_DEFINE(PP,pp)		IF_FUNCTION_PARAM_DEFINE2(PP,pp)
#define IF_DP_SRC_FUNCTION_PARAM_CALL(P)			IF_FUNCTION_PARAM_CALL2(P) 
#define IF_DP_SRC_TEMPALTE_PARAM_DEFINE(P)			IF_TEMPALTE_PARAM_DEFINE2(P) 

#elif	IF_DP_SRC_FUNCTION_PARAM_NUM <= 4
#define IF_DP_SRC_FUNCTION_PARAM_DEFINE(PP,pp)		IF_FUNCTION_PARAM_DEFINE3(PP,pp)
#define IF_DP_SRC_FUNCTION_PARAM_CALL(P)			IF_FUNCTION_PARAM_CALL3(P) 
#define IF_DP_SRC_TEMPALTE_PARAM_DEFINE(P)			IF_TEMPALTE_PARAM_DEFINE3(P) 

#elif	IF_DP_SRC_FUNCTION_PARAM_NUM <= 5
#define IF_DP_SRC_FUNCTION_PARAM_DEFINE(PP,pp)		IF_FUNCTION_PARAM_DEFINE4(PP,pp)
#define IF_DP_SRC_FUNCTION_PARAM_CALL(P)			IF_FUNCTION_PARAM_CALL4(P) 
#define IF_DP_SRC_TEMPALTE_PARAM_DEFINE(P)			IF_TEMPALTE_PARAM_DEFINE4(P) 

#elif	IF_DP_SRC_FUNCTION_PARAM_NUM <= 6
#define IF_DP_SRC_FUNCTION_PARAM_DEFINE(PP,pp)		IF_FUNCTION_PARAM_DEFINE5(PP,pp)
#define IF_DP_SRC_FUNCTION_PARAM_CALL(P)			IF_FUNCTION_PARAM_CALL5(P) 
#define IF_DP_SRC_TEMPALTE_PARAM_DEFINE(P)			IF_TEMPALTE_PARAM_DEFINE5(P) 

#elif	IF_DP_SRC_FUNCTION_PARAM_NUM <= 7
#define IF_DP_SRC_FUNCTION_PARAM_DEFINE(PP,pp)		IF_FUNCTION_PARAM_DEFINE6(PP,pp)
#define IF_DP_SRC_FUNCTION_PARAM_CALL(P)			IF_FUNCTION_PARAM_CALL6(P) 
#define IF_DP_SRC_TEMPALTE_PARAM_DEFINE(P)			IF_TEMPALTE_PARAM_DEFINE6(P) 

#elif	IF_DP_SRC_FUNCTION_PARAM_NUM <= 8
#define IF_DP_SRC_FUNCTION_PARAM_DEFINE(PP,pp)		IF_FUNCTION_PARAM_DEFINE7(PP,pp)
#define IF_DP_SRC_FUNCTION_PARAM_CALL(P)			IF_FUNCTION_PARAM_CALL7(P) 
#define IF_DP_SRC_TEMPALTE_PARAM_DEFINE(P)			IF_TEMPALTE_PARAM_DEFINE7(P) 

#elif	IF_DP_SRC_FUNCTION_PARAM_NUM <= 9
#define IF_DP_SRC_FUNCTION_PARAM_DEFINE(PP,pp)		IF_FUNCTION_PARAM_DEFINE8(PP,pp)
#define IF_DP_SRC_FUNCTION_PARAM_CALL(P)			IF_FUNCTION_PARAM_CALL8(P) 
#define IF_DP_SRC_TEMPALTE_PARAM_DEFINE(P)			IF_TEMPALTE_PARAM_DEFINE8(P) 

#elif	IF_DP_SRC_FUNCTION_PARAM_NUM <= 10
#define IF_DP_SRC_FUNCTION_PARAM_DEFINE(PP,pp)		IF_FUNCTION_PARAM_DEFINE9(PP,pp)
#define IF_DP_SRC_FUNCTION_PARAM_CALL(P)			IF_FUNCTION_PARAM_CALL9(P) 
#define IF_DP_SRC_TEMPALTE_PARAM_DEFINE(P)			IF_TEMPALTE_PARAM_DEFINE9(P) 
#else
#error	NOT SUPPORT PARAM NUM > 10
#endif

#undef IF_DP_TARGET_FUNCTION_PARAM_SPLIT

#if IF_DP_TARGET_FUNCTION_PARAM_NUM == 0
#define IF_DP_TARGET_FUNCTION_PARAM_SPLIT 
#else
#define IF_DP_TARGET_FUNCTION_PARAM_SPLIT ,
#endif

template<typename R, IF_TEMPALTE_PARAM_DEFINE(P), IF_DP_SRC_TEMPALTE_PARAM_DEFINE(DP)>
class IFFunctorDefaultParam<IFFunctor<R(IF_FUNCTION_PARAM_CALL(P))>,IFFunctorParam<IF_DP_SRC_FUNCTION_PARAM_CALL(DP)>> : public IFFunctor<R(IF_DP_TARGET_FUNCTION_PARAM_CALL(P))>
{
public:
	typedef IFFunctor<R(IF_DP_TARGET_FUNCTION_PARAM_CALL(P))> TARGET_FUNCTOR ;

	IFFunctorDefaultParam(IFFunctor<R(IF_FUNCTION_PARAM_CALL(P))>* pFun,const IFFunctorParam<IF_DP_SRC_FUNCTION_PARAM_CALL(DP)>& dp )
		:m_spFun(pFun),m_dps(dp)
	{

	}

	virtual R operator()(IF_DP_TARGET_FUNCTION_PARAM_DEFINE(P,p)) const
	{
		return (*m_spFun)(IF_DP_TARGET_FUNCTION_PARAM_CALL(p) IF_DP_TARGET_FUNCTION_PARAM_SPLIT IF_DP_SRC_FUNCTION_PARAM_CALL(m_dps.m_dp));
	}

	IFRefPtr<IFFunctor<R(IF_FUNCTION_PARAM_CALL(P))>> m_spFun;
	IFFunctorParam<IF_DP_SRC_FUNCTION_PARAM_CALL(DP)> m_dps;
};



#endif