/*
The MIT License (MIT)
Copyright © 2014 Huang Cong

Permission is hereby granted, free of charge, to any person obtaining a 
copy of this software and associated documentation files (the “Software”), 
to deal in the Software without restriction, including without limitation 
the rights to use, copy, modify, merge, publish, distribute, sublicense, 
and/or sell copies of the Software, and to permit persons to whom the 
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS 
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN 
THE SOFTWARE.
*/
#ifndef IF_REPEAT_INCLUDE_FILE0
#define IF_REPEAT_INCLUDE_FILE0
#endif

#ifndef IF_REPEAT_INCLUDE_FILE1
#define IF_REPEAT_INCLUDE_FILE1
#endif

#ifndef IF_REPEAT_INCLUDE_FILE2
#define IF_REPEAT_INCLUDE_FILE2
#endif

#ifndef IF_REPEAT_INCLUDE_FILE3
#define IF_REPEAT_INCLUDE_FILE3
#endif

#if IF_REPEAT_INCLUDE_NUM > 0
#define IF_REPEAT_INCLUDE_INDEX 0
#include	IF_REPEAT_INCLUDE_FILE0
#include	IF_REPEAT_INCLUDE_FILE1
#include	IF_REPEAT_INCLUDE_FILE2
#include	IF_REPEAT_INCLUDE_FILE3
#endif

#if IF_REPEAT_INCLUDE_NUM > 1
#undef IF_REPEAT_INCLUDE_INDEX
#define IF_REPEAT_INCLUDE_INDEX 1

#include	IF_REPEAT_INCLUDE_FILE0
#include	IF_REPEAT_INCLUDE_FILE1
#include	IF_REPEAT_INCLUDE_FILE2
#include	IF_REPEAT_INCLUDE_FILE3
#endif

#if IF_REPEAT_INCLUDE_NUM > 2
#undef IF_REPEAT_INCLUDE_INDEX
#define IF_REPEAT_INCLUDE_INDEX 2
#include	IF_REPEAT_INCLUDE_FILE0
#include	IF_REPEAT_INCLUDE_FILE1
#include	IF_REPEAT_INCLUDE_FILE2
#include	IF_REPEAT_INCLUDE_FILE3
#endif

#if IF_REPEAT_INCLUDE_NUM > 3
#undef IF_REPEAT_INCLUDE_INDEX
#define IF_REPEAT_INCLUDE_INDEX 3
#include	IF_REPEAT_INCLUDE_FILE0
#include	IF_REPEAT_INCLUDE_FILE1
#include	IF_REPEAT_INCLUDE_FILE2
#include	IF_REPEAT_INCLUDE_FILE3
#endif

#if IF_REPEAT_INCLUDE_NUM > 4
#undef IF_REPEAT_INCLUDE_INDEX
#define IF_REPEAT_INCLUDE_INDEX 4
#include	IF_REPEAT_INCLUDE_FILE0
#include	IF_REPEAT_INCLUDE_FILE1
#include	IF_REPEAT_INCLUDE_FILE2
#include	IF_REPEAT_INCLUDE_FILE3
#endif

#if IF_REPEAT_INCLUDE_NUM > 5
#undef IF_REPEAT_INCLUDE_INDEX
#define IF_REPEAT_INCLUDE_INDEX 5
#include	IF_REPEAT_INCLUDE_FILE0
#include	IF_REPEAT_INCLUDE_FILE1
#include	IF_REPEAT_INCLUDE_FILE2
#include	IF_REPEAT_INCLUDE_FILE3
#endif

#if IF_REPEAT_INCLUDE_NUM > 6
#undef IF_REPEAT_INCLUDE_INDEX
#define IF_REPEAT_INCLUDE_INDEX 6
#include	IF_REPEAT_INCLUDE_FILE0
#include	IF_REPEAT_INCLUDE_FILE1
#include	IF_REPEAT_INCLUDE_FILE2
#include	IF_REPEAT_INCLUDE_FILE3
#endif

#if IF_REPEAT_INCLUDE_NUM > 7
#undef IF_REPEAT_INCLUDE_INDEX
#define IF_REPEAT_INCLUDE_INDEX 7
#include	IF_REPEAT_INCLUDE_FILE0
#include	IF_REPEAT_INCLUDE_FILE1
#include	IF_REPEAT_INCLUDE_FILE2
#include	IF_REPEAT_INCLUDE_FILE3
#endif

#if IF_REPEAT_INCLUDE_NUM > 8
#undef IF_REPEAT_INCLUDE_INDEX
#define IF_REPEAT_INCLUDE_INDEX 8
#include	IF_REPEAT_INCLUDE_FILE0
#include	IF_REPEAT_INCLUDE_FILE1
#include	IF_REPEAT_INCLUDE_FILE2
#include	IF_REPEAT_INCLUDE_FILE3
#endif

#if IF_REPEAT_INCLUDE_NUM > 9
#undef IF_REPEAT_INCLUDE_INDEX
#define IF_REPEAT_INCLUDE_INDEX 9
#include	IF_REPEAT_INCLUDE_FILE0
#include	IF_REPEAT_INCLUDE_FILE1
#include	IF_REPEAT_INCLUDE_FILE2
#include	IF_REPEAT_INCLUDE_FILE3
#endif

#if IF_REPEAT_INCLUDE_NUM > 10
#undef IF_REPEAT_INCLUDE_INDEX
#define IF_REPEAT_INCLUDE_INDEX 10
#include	IF_REPEAT_INCLUDE_FILE0
#include	IF_REPEAT_INCLUDE_FILE1
#include	IF_REPEAT_INCLUDE_FILE2
#include	IF_REPEAT_INCLUDE_FILE3
#endif

#if IF_REPEAT_INCLUDE_NUM > 11
#undef IF_REPEAT_INCLUDE_INDEX
#define IF_REPEAT_INCLUDE_INDEX 11
#include	IF_REPEAT_INCLUDE_FILE0
#include	IF_REPEAT_INCLUDE_FILE1
#include	IF_REPEAT_INCLUDE_FILE2
#include	IF_REPEAT_INCLUDE_FILE3
#endif

#if IF_REPEAT_INCLUDE_NUM > 12
#undef IF_REPEAT_INCLUDE_INDEX
#define IF_REPEAT_INCLUDE_INDEX 12
#include	IF_REPEAT_INCLUDE_FILE0
#include	IF_REPEAT_INCLUDE_FILE1
#include	IF_REPEAT_INCLUDE_FILE2
#include	IF_REPEAT_INCLUDE_FILE3
#endif